DoAnASP/Controllers/LikesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnASP.Data;
using DoAnASP.Models;

namespace DoAnASP.Controllers
{
    public class LikesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LikesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Likes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Likes.Include(l => l.Song).Include(l => l.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Likes/Details/5
        public async Task<IActionResult> Details(string userId, int songId)
        {
            
            if (userId == null || songId == 0)
            {
                return NotFound();
            }

            var like = await _context.Likes
                .Include(l => l.Song)
                .Include(l => l.User)
                .FirstOrDefaultAsync(m => m.UserID == userId && m.SongID == songId);
            if (like == null)
            {
                return NotFound();
            }

            return View(like);
        }


        // GET: Likes/Create
        public IActionResult Create()
        {
            ViewData["SongID"] = new SelectList(_context.Songs, "SongID", "Title");
            ViewData["UserID"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "UserName");
            return View();
        }

        // POST: Likes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserID,SongID,CreatedAt")] Like like)
        {
            ModelState.Remove("User");
            ModelState.Remove("Song");

            if (ModelState.IsValid)
            {
                _context.Add(like);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SongID"] = new SelectList(_context.Songs, "SongID", "Title", like.SongID);
            ViewData["UserID"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "UserName", like.UserID);
            return View(like);
        }

        // GET: Likes/Edit/5
        public async Task<IActionResult> Edit(string userId, int songId)
        {
            if (userId == null || songId == 0)
            {
                return NotFound();
            }

            var like = await _context.Likes.FindAsync(userId, songId); // Lưu ý sửa FindAsync
            if (like == null)
            {
                return NotFound();
            }
            ViewData["SongID"] = new SelectList(_context.Songs, "SongID", "Title", like.SongID);
            ViewData["UserID"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "UserName", like.UserID);
            return View(like);
        }


        // POST: Likes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string userId, int songId, [Bind("UserID,SongID,CreatedAt")] Like like)
        {
            ModelState.Remove("User");
            ModelState.Remove("Song");

            // Kiểm tra nếu UserID hoặc SongID không khớp
            if (userId != like.UserID || songId != like.SongID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(like);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LikeExists(like.UserID, like.SongID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SongID"] = new SelectList(_context.Songs, "SongID", "Title", like.SongID);
            ViewData["UserID"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "UserName", like.UserID);
            return View(like);
        }


        // GET: Likes/Delete/5
        public async Task<IActionResult> Delete(string userId, int songId)
        {
            if (userId == null || songId == 0)
            {
                return NotFound();
            }

            var like = await _context.Likes
                .Include(l => l.Song)
                .Include(l => l.User)
                .FirstOrDefaultAsync(m => m.UserID == userId && m.SongID == songId);
            if (like == null)
            {
                return NotFound();
            }

            return View(like);
        }


        // POST: Likes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string userId, int songId)
        {
            var like = await _context.Likes.FindAsync(userId, songId);
            if (like != null)
            {
                _context.Likes.Remove(like);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LikeExists(string userId, int songId)
        {
            return _context.Likes.Any(e => e.UserID == userId && e.SongID == songId);
        }

    }
}

DoAnASP/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnASP.Data;
using DoAnASP.Models;
using Mono.TextTemplating;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Text.Json;

namespace DoAnASP.Controllers
{
    public class SongsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<SongsController> _logger;
      
        public SongsController(ApplicationDbContext context, ILogger<SongsController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: Songs
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Songs.Include(s => s.Album).Include(s => s.Artist).Include(s => s.Genre);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Songs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs
                .Include(s => s.Album)
                .Include(s => s.Artist)
                .Include(s => s.Genre)
                .FirstOrDefaultAsync(m => m.SongID == id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }

        // GET: Songs/Create
        public IActionResult Create()
        {
            ViewData["AlbumID"] = new SelectList(_context.Albums, "AlbumID", "Title");
            ViewData["ArtistID"] = new SelectList(_context.Artist, "Id", "Name");
            ViewData["GenreID"] = new SelectList(_context.Genre, "GenreID", "Name");
            return View();
        }

        // POST: Songs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SongID,AlbumID,ArtistID,GenreID,Title,AudioFile,Duration,PlayCount,IsExplicit,Image")] Song song, [Bind] IFormFile AudioFileUpLoad, [Bind] IFormFile ImageUpLoad)
        {

            ViewData["AlbumID"] = new SelectList(_context.Albums, "AlbumID", "Title", song.AlbumID);
            ViewData["ArtistID"] = new SelectList(_context.Artist, "Id", "Name", song.ArtistID);
            ViewData["GenreID"] = new SelectList(_context.Genre, "GenreID", "Name", song.GenreID);

            if (AudioFileUpLoad != null && AudioFileUpLoad.Length > 0)
            {
                // Lấy tên file
                var audioFileName = Path.GetFileName(AudioFileUpLoad.FileName);
                // Đường dẫn lưu file
                var audioPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\audios", audioFileName);

                // Sao chép file
                using (var stream = new FileStream(audioPath, FileMode.Create))
                {
                    await AudioFileUpLoad.CopyToAsync(stream);
                }

                // Lưu tên file vào model
                song.AudioFile = audioFileName;

            }
            else
            {
                ModelState.AddModelError("AudioFile", "Vui lòng tải lên file âm thanh.");
                return View();
            }

            if (ImageUpLoad != null && ImageUpLoad.Length > 0)
            {
                // Lấy tên file
                var imageFileName = Path.GetFileName(ImageUpLoad.FileName);
                // Đường dẫn lưu file
                var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\pictures", imageFileName);

                // Sao chép file
                using (var stream = new FileStream(imagePath, FileMode.Create))
                {
                    await ImageUpLoad.CopyToAsync(stream);
                }

                // Lưu tên file vào model
                song.Image = imageFileName;
            }
            else
            {
                ModelState.AddModelError("Image", "Vui lòng tải lên ảnh bìa.");
                return View();
            }



            ModelState.Remove("Album");
            ModelState.Remove("Artist");
            ModelState.Remove("Genre");
            ModelState.Remove("Likes");
            ModelState.Remove("Comments");
            ModelState.Remove("PlaylistSongs");

            if (ModelState.IsValid)
            {
                _context.Add(song);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


            return View(song);
        }

        // GET: Songs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }
            ViewData["AlbumID"] = new SelectList(_context.Albums, "AlbumID", "Title", song.AlbumID);
            ViewData["ArtistID"] = new SelectList(_context.Artist, "Id", "Name", song.ArtistID);
            ViewData["GenreID"] = new SelectList(_context.Genre, "GenreID", "Name", song.GenreID);
            return View(song);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SongID,AlbumID,ArtistID,GenreID,Title,AudioFile,Duration,PlayCount,IsExplicit,Image")] Song song, [Bind] IFormFile AudioFileUpLoad, [Bind] IFormFile ImageUpLoad)
        {

            var current_song = _context.Songs.AsNoTracking().FirstOrDefault(s => s.SongID == id);

            if (song.ArtistID == null)
            {
                song.ArtistID = current_song.ArtistID;
            }

            if (song.AlbumID == null)
            {
                song.AlbumID = current_song.AlbumID;
            }

            if (song.GenreID == null)
            {
                song.GenreID = current_song.GenreID;
            }


            if (AudioFileUpLoad != null && AudioFileUpLoad.Length > 0)
            {
                // Lấy tên file
                var audioFileName = Path.GetFileName(AudioFileUpLoad.FileName);
                // Đường dẫn lưu file
                var audioPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\audios", audioFileName);

                // Sao chép file
                using (var stream = new FileStream(audioPath, FileMode.Create))
                {
                    await AudioFileUpLoad.CopyToAsync(stream);
                }

                // Lưu tên file vào model
                song.AudioFile = audioFileName;

            }



            if (ImageUpLoad != null && ImageUpLoad.Length > 0)
            {
                // Lấy tên file
                var imageFileName = Path.GetFileName(ImageUpLoad.FileName);
                // Đường dẫn lưu file
                var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\pictures", imageFileName);

                // Sao chép file
                using (var stream = new FileStream(imagePath, FileMode.Create))
                {
                    await ImageUpLoad.CopyToAsync(stream);
                }

                // Lưu tên file vào model
                song.Image = imageFileName;
            }

            ModelState.Remove("ImageUpLoad");
            ModelState.Remove("AudioFileUpLoad");
            ModelState.Remove("Album");
            ModelState.Remove("Artist");
            ModelState.Remove("Genre");
            ModelState.Remove("Likes");
            ModelState.Remove("Comments");
            ModelState.Remove("PlaylistSongs");


            if (id != song.SongID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(song);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SongExists(song.SongID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }


            ViewData["AlbumID"] = new SelectList(_context.Albums, "AlbumID", "Title", song.AlbumID);
            ViewData["ArtistID"] = new SelectList(_context.Artist, "Id", "Name", song.ArtistID);
            ViewData["GenreID"] = new SelectList(_context.Genre, "GenreID", "Name", song.GenreID);

            return View(song);
        }

        // GET: Songs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Songs
                .Include(s => s.Album)
                .Include(s => s.Artist)
                .Include(s => s.Genre)
                .FirstOrDefaultAsync(m => m.SongID == id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }

        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

DoAnASP/Views/Shared/_Layout - Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hồ sơ người dùng</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookWebsite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="btn btn-light" asp-area="Identity" asp-page="/Account/Login">Đăng ký</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-link text-secondary me-2" asp-action="Index" asp-controller="Home">Trang chủ</a>
                            </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DoAnASP/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery

@{
    var token = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <meta name="__RequestVerificationToken" content="@token">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/spotify.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/playlist-song-styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Home/Prenium/site.css" asp-append-version="true" />
</head>
<body>
    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Audio.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DoAnASP/Views/Shared/_Layout_Login_Register.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/Login/site.css" />
</head>
<body>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DoAnASP/Views/Shared/_Layout_Manager.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Quản lý Âm nhạc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <style>
        body, html {
            height: 100%;
            margin: 0;
            overflow: hidden; /* Loại bỏ thanh cuộn không cần thiết */
        }

        #wrapper {
            display: flex;
            height: 100vh; /* Chiều cao toàn màn hình */
            overflow: hidden;
        }

        #sidebar-wrapper {
            width: 250px; /* Chiều rộng của sidebar */
            height: 100vh; /* Chiều cao toàn màn hình */
            position: fixed;
            background-color: #343a40; /* Màu nền của sidebar */
        }

        #page-content-wrapper {
            margin-left: 250px; /* Đẩy nội dung chính sang bên phải */
            width: calc(100% - 250px); /* Chiếm phần còn lại của màn hình */
            overflow-y: auto;
            background-color: #212529; /* Cho phép cuộn dọc khi nội dung quá dài */
        }

            #page-content-wrapper.toggled {
                margin-left: 0; /* Khi sidebar được thu gọn */
                width: 100%; /* Nội dung chiếm toàn màn hình */
            }

        footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            height: 40px;
            text-align: center;
        }

        /* Sidebar - Hover effect */
        #sidebar-wrapper .list-group-item {
            transition: background-color 0.3s ease, color 0.3s ease;
        }

            #sidebar-wrapper .list-group-item:hover {
                background-color: #495057;
                color: #ffc107;
            }

        /* Navbar - Add shadow and smooth hover effect */
        .navbar {
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            transition: background-color 0.3s ease;
        }

            .navbar:hover {
                background-color: #212529;
            }

        /* Footer - Styling */
        footer.footer {
            background-color: #212529;
            color: #adb5bd;
            font-size: 0.9rem;
        }

            footer.footer:hover {
                background-color: #343a40;
                color: #ffffff;
            }


        /* Smooth transition for toggling sidebar */
        #wrapper {
            transition: margin-left 0.3s ease;
        }


        #sidebar-wrapper {
            transition: width 0.3s ease;
        }

            #sidebar-wrapper .list-group-item-action {
                background-color: #343A40; /* Màu nền mặc định */
                color: white; /* Màu chữ mặc định */
                transition: background-color 0.3s, color 0.3s; /* Thêm hiệu ứng chuyển màu mượt mà */
            }

                #sidebar-wrapper .list-group-item-action:hover {
                    background-color: #495057; /* Màu nền khi di chuột vào */
                    color: white; /* Màu chữ khi di chuột vào */
                }


        #page-content-wrapper.toggled {
            transition: margin-left 0.3s ease;
        }

        /* Scrollbar customization */
        #page-content-wrapper::-webkit-scrollbar {
            width: 8px;
        }

        #page-content-wrapper::-webkit-scrollbar-thumb {
            background: #6c757d;
            border-radius: 4px;
        }

            #page-content-wrapper::-webkit-scrollbar-thumb:hover {
                background: #495057;
            }

    </style>
</head>
<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <div class="sidebar-heading text-center py-4 text-white fs-4 fw-bold">
                <i class="bi bi-music-note-beamed"></i> Quản lý Âm nhạc
            </div>
            <div class="list-group list-group-flush">
                <a asp-controller="Home" asp-action="Index" class="list-group-item list-group-item-action text-white">
                    <i class="bi bi-house-door me-2"></i> Trang chủ
                </a>
                <a asp-controller="Songs" asp-action="Index" class="list-group-item list-group-item-action text-white">
                    <i class="bi bi-music-note-list me-2"></i> Quản lý Bài hát
                </a>
                <a asp-controller="Artists" asp-action="Index" class="list-group-item list-group-item-action text-white">
                    <i class="bi bi-person me-2"></i> Quản lý Nghệ sĩ
                </a>
                <a asp-controller="Albums" asp-action="Index" class="list-group-item list-group-item-action text-white">
                    <i class="bi bi-vinyl me-2"></i> Quản lý Album
                </a>
                <a asp-controller="Genres" asp-action="Index" class="list-group-item list-group-item-action text-white">
                    <i class="bi bi-tags me-2"></i> Quản lý Thể loại
                </a>
                <a asp-controller="Playlists" asp-action="Index" class="list-group-item list-group-item-action text-white">
                    <i class="bi bi-list-ul me-2"></i> Quản lý Playlist
                </a>
                <a asp-controller="PlaylistSongs" asp-action="Index" class="list-group-item list-group-item-action text-white"> 
                    <i class="bi bi-music-note-beamed me-2"></i> Quản lý bài hát Playlist 
                </a>
                <a asp-controller="Likes" asp-action="Index" class="list-group-item list-group-item-action text-white">
                    <i class="bi bi-hand-thumbs-up me-2"></i> Quản lý Lượt thích
                </a>
                <a asp-controller="Follows" asp-action="Index" class="list-group-item list-group-item-action text-white">
                    <i class="bi bi-person-check me-2"></i> Quản lý Lượt theo dõi
                </a>
            </div>

        </div>


        <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
                <div class="container-fluid">
                    <button class="btn btn-dark" id="menu-toggle"><i class="bi bi-list"></i></button>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">                         
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
                                    <i class="bi bi-person-circle"></i> @User.Identity?.Name.Substring(0, (int)@User.Identity?.Name.IndexOf('@'))
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hồ sơ</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                            <button class="dropdown-item" type="submit" class="nav-link btn btn-link text-light"> Đăng Xuất</button>
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <div class="container-fluid" style="padding: 0px;">
                <main role="main">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="footer bg-dark text-white py-2">
        <div class="container" style="background-color: none;">
            &copy; 2024 - Quản lý Âm nhạc
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
</body>
</html>

DoAnASP/Views/Shared/_SearchResults.cshtml
@model IEnumerable<DoAnASP.Models.Song>

<div class="media-grid">
    @foreach (var item in Model)
    {
        <div class="media-card"
             data-id="@item.SongID"
             data-audio="/audios/@item.AudioFile"
             data-title="@item.Title"
             data-artist="@item.Artist.Name"
             data-album="@item.Album.Title"
             data-genre="@item.Genre.Name"
             data-duration="@item.Duration"
             data-explicit="@item.IsExplicit.ToString().ToLower()">
            <div class="media-card-image">
                <a href="/Home/Details/@item.SongID" class="details-link" data-id="@item.SongID">
                    <img src="/pictures/@item.Image" alt="@item.Title" />
                </a>
                <button class="play-button" onclick="togglePlay(this)">
                    <i class="bi bi-play-fill"></i>
                </button>
            </div>
            <div class="media-card-content">
                <h3 class="media-title">@item.Title</h3>
                <p class="media-description">@item.Artist.Name</p>
            </div>
        </div>
    }
</div>